version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
        - image: circleci/python:3.8.0
    steps:
      - checkout
      - run: sudo python -m pip install --upgrade pip
      - run: sudo pip install -r requirements.txt
#      - run: python -m pytest --junitxml=junit/test-results.xml --cov=src --cov-report=xml --cov-report=html test/unit
#      - codecov/upload:
#          file: junit/test-results.xml
      - run: coverage run -m pytest
      - run: coverage report
      - run: coverage html
      - store_artifacts:
          path: htmlcov