import os

ENVIRONMENT = "local" if not os.environ.get("CI", False) else "CI"

DEFAULT_COMPETENCY = [0]
DEFAULT_CONTRACTED_HOURS = 36
DEFAULT_DAILY_REST_HOURS = 8
DEFAULT_WEEKLY_REST_HOURS = 36
DEFAULT_DAILY_OFFSET = 4

DAYS_IN_WEEK = 7
SATURDAY_INDEX = 5
SUNDAY_INDEX = 6

DESIRED_SHIFT_DURATION = [6, 12]
ALLOWED_SHIFT_DURATION = [2, 14]

TIME_DEFINING_SHIFT_DAY = 24
